FROM node:20

WORKDIR /usr/src/app

# Copy dependency definitions first
COPY package.json yarn.lock ./

RUN yarn install

# Copy all source code
COPY . .

# Copy env file
COPY .env .env

# Expose typical NestJS port
EXPOSE 3000

# Start in watch mode
CMD ["yarn", "start:dev"]
